/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_SystemClock_Companion */

#ifndef _Included_android_os_SystemClock_Companion
#define _Included_android_os_SystemClock_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_SystemClock_Companion
 * Method:    uptimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_SystemClock_00024Companion_uptimeMillis
  (JNIEnv *, jobject);

/*
 * Class:     android_os_SystemClock_Companion
 * Method:    elapsedRealtime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_SystemClock_00024Companion_elapsedRealtime
  (JNIEnv *, jobject);

/*
 * Class:     android_os_SystemClock_Companion
 * Method:    elapsedRealtimeNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_SystemClock_00024Companion_elapsedRealtimeNanos
  (JNIEnv *, jobject);

/*
 * Class:     android_os_SystemClock_Companion
 * Method:    currentThreadTimeMillis
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_SystemClock_00024Companion_currentThreadTimeMillis
  (JNIEnv *, jobject);

/*
 * Class:     android_os_SystemClock_Companion
 * Method:    currentThreadTimeMicro
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_SystemClock_00024Companion_currentThreadTimeMicro
  (JNIEnv *, jobject);

/*
 * Class:     android_os_SystemClock_Companion
 * Method:    currentTimeMicro
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_os_SystemClock_00024Companion_currentTimeMicro
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
