/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cfig_AHelper_Companion */

#ifndef _Included_cfig_AHelper_Companion
#define _Included_cfig_AHelper_Companion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cfig_AHelper_Companion
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cfig_AHelper_00024Companion_strerror
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
